# This is a basic workflow to help you get started with Actions

name: Demo1_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Step 4: Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Run tests
      - name: Run tests
        run: ./gradlew test

      # Step 6: Upload APK artifact (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/debug/app-debug.apk
